format_version: 10
pipelines:
  expense-tf-apply:
    group: Terraform
    materials:
      git-1ab79a5:
        git: https://github.com/devopsnagesha/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:2H5w3HEbRZYWsYxkf1plLA==:wz9HB3hZWfau6oPVGmkxS57qnCEkThvP88Ib4AAOupk=
    stages:
    - DEV:
        fetch_materials: true
        environment_variables:
          env: dev
        approval:
          type: manual
        jobs:
          ansible-playbook:
            tasks:
            - exec: {command: terraform, arguments: [ "init", "-backend-config=env-dev/state.tfvars" ], run_if: passed}
            - exec: {command: terraform, arguments: [ "apply", "-var-file=env-dev/main.tfvars", "-auto-approve" ], run_if: passed}

